! FRR configuration for R1
!
frr defaults datacenter
!
fpm connection ip 172.17.0.1 port 2620
router bgp 65041
bgp router-id 192.168.63.2
timers bgp 3 9
neighbor PEER peer-group
neighbor PEER ebgp-multihop
neighbor PEER timers connect 5
neighbor PEER advertisement-interval 5
neighbor 192.168.63.1 remote-as 65040
neighbor 192.168.63.1 peer-group PEER

bgp router-id fd63::2
neighbor fd63::1 remote-as 65040
neighbor fd63::1 peer-group PEER
!
address-family ipv4 unicast
    network 172.17.4.0/24
    neighbor 192.168.63.1 activate
    no neighbor fd63::1 activate
exit-address-family
!
address-family ipv6 unicast
    network 2a0b:4e07:c4:104::/64
    neighbor fd63::1 activate
    no neighbor 192.168.63.1 activate
exit-address-family
!
log stdout